### ISSUE TITLE
Audio is not working

### ISSUE THREAD

**Issue by kylergib** [kylergib/Asus-Zephyrus-M-gm501gs-Mojave#1]
Audio is not working, internal speakers are detected, but you cannot hear any sound. Mic is still working properly.

Not sure when this started, unsure if it is happening on current Clover folder I have uploaded, will do clean install and test. Could be something I have installed separately.

**Comment by kylergib** [comment]
Did not work with clean install and clean Clover folder that I uploaded.

**Comment by williambj1** [comment]
Hi @kylergib 
Try AppleALC layout 21 for ALC294
Btw, is the space large enough to store a DW1830 inside?
I have a GX531 and I saw you on Gitter.

**Comment by kylergib** [comment]
@williambj1 I actually got it to work, but forgot to close out my issue. Thanks for the response though, I got it to work with adding layout 13, but for some reason I deleted codeccommander.kext, so it wasn't working properly, once I added that back, it works fine! and also, the DW1830 fits, is sort of a tight squeeze, I can upload a picture of what it looks like in a little bit if you would like.  Any idea how to get headphone jack to work? That is the last thing on my list that I have found out that does not work.

**Comment by williambj1** [comment]
No, thank you very much, the picture not necessary, I just want to make sure.
**Layout 21** for ALC294 has headphones working properly but no automatic switch for inputs, at least it's the best ID so far patched by Andres ZeroCross @andreszerocross, you might saw him before in Gitter as well.
BTW, is your keyboard backlight working? And level controlling?
Thanks for your reply!

**Comment by kylergib** [comment]
gotcha will try layout 21 then! and it is not working, I have tried to get it working but gave up lol

**Comment by andreszerocross** [comment]
I can make Internal and external mic be automatic switch,, i make it not automatic because some people need manual select input,, so i made it to not automatic.
